GitAlias/gitalias

- gitalias.txt
`git var GIT_EDITOR` is better than ${VISUAL:-${EDITOR:-vi}} because
it takes into account all variables: GIT_EDITOR, VISUAL and EDITOR,
and falls back to the platform's default.
> Use `git var GIT_EDITOR` to call editor

- gitalias.txt
Now aliases shown as table that is better for understanding.
> Improve command for showing alias list

- gitalias.txt
Add rename alias:
Usage:
git rename-(local|global)-alias <alias existing name> <new alias name>
<s>git rename-alias <alias existing name> <new alias name></s>
- Choose Local or global to use `--global` or `--local` options
- First parameter `<alias existing name>` must be an existing alias.
- Second parameter `<new alias name>`  must be an alias that does not exist.
- First parameter and second parameter must be different.
- There must be two parameters
Examples:
Success:
git rename-local-alias ci comm
git rename-global-alias ci comm
<s>git rename-alias ci comm</s>
<s>Alias comm renamed to ci</s>
Error:
git rename-local-alias any ci
Usage: git rename-alias <alias existing name> <new alias name>
The alias you are going to rename must exist and new name must not exist.
git …
> Add rename-alias alias at alias management

- gitalias.txt
Add `discard` and `discard-all` aliases:
Usages:
git discard file-name
- Parameter would be the file name or pattern to discard
git discard-all
- Discards all the working directory.
--- 
Why discard? 
It is an action which is used in several git GUIs, for example Source Tree.
> Add discard and discard-all aliases

- README.md
- gitalias.txt
the push command also run with the parameter and it gives error.
```sh
git put test 
[master b9f5249] test
1 file changed, 1 insertion(+), 1 deletion(-)
fatal: 'test' does not appear to be a git repository
fatal: Could not read from remote repository.
```
> put alias error

- gitalias.txt
I fixed a few aliases which did not behave at they should (at least under `git 2.23.0`), proposed a few simplifications and added a VIm modeline and emacs mode to enable syntax highlighting.
Any feedback appreciated.
> fixes and simplification for existing aliases

- gitalias.txt
I am currently using topics, and synchronizing with the `topic-base-branch-name` using rebase is not useful when the topic has already been published to the remote. In this scenario, `topic-pull-merge` is a better way to synchronize than `topic-pull-rebase` and can help to solve local merge conflicts.
> Add topic-pull-merge

- gitalias.txt
The repo is awesome! utilizing it every day only to find new git commands I was unaware of until then.
This pr is to propose a `--no-guess` option to the `checkout` command
Often auto-completion in `checkout` results in unwanted remote repositories.
This option enables users to checkout only useful branches
Source:
https://stackoverflow.com/questions/6623649/disable-auto-completion-of-remote-branches-in-git-bash
> feat(checkout): add --no-guess option

- gitalias.txt
Enable the topic base branch to be set on a per-repository basis by
storing the branch in the `GitAlias.topic.baseBranch` configuration
setting.
Added the `topic-base-branch-name-set` alias to update the setting
> Add configurable topic base branch

- gitalias.txt
Currently points to `gitlias.com`, should point to `gitalias.com`
> Fix gitalias.com typo

- gitalias.txt
After using this gitaliases file, I found myself often using the `git cpa`, `git cpc`, `git rba`, & `git rbc` aliases.
When doing merges, my instinct is to type `git ma` & `git mc` commands, but these are not currently available.
I have added these aliases to my local git config, but thought I'd go ahead & and a PR to see if anyone else would find these useful.
> Add 'ma' and 'mc' aliases

- gitalias.txt
Running git commands, via xargs, without input may lead to spurious error messages at best.
At worst it might have unforseen bad effects especially with remove and delete commands.
Use xargs' "-r" option to run only when non-zero input from the pipe is received.
> prevent xargs running when input (from pipe) is empty

- gitalias.txt
No backslash (`\`) character is needed before arguments.
> Fix diff-chunk

- gitalias.txt
grep should pipe into xargs here.
> fix missing | between grep and xargs in cull-remote-branches

- gitalias.txt
Looks like the interactive rebase alias wasn't using the `--interactive` flag and was using `--skip`.
> Fix 'rbi' alias

- README.md
- doc/examples/examples.md
- doc/install/install.md
In several files the old "master" branch is still listed.
Even though github does an automatic redirect I changed it once to the current "main" branch.
> feature/change-refs-to-main Change references to main instead of master

- README.md
- doc/install/index.html
- doc/install/index.md
Tested on Windows 11. I did not retest, but I am pretty sure it worked like this on Windows 10 as well.
I decided to keep the instructions in the gitalias.txt as is and to slightly rephrase the main readme so people would more likely really look into the installation instructions.
> Documentation install on windows

- doc/examples/index.md
- doc/git-snapshot/index.md
- gitalias.txt
This PR suggests adding `--index` to the `git apply` command
that ends the `git snapshot` alias.
The reason is that otherwise, although, as you rightly say,
the working tree is restored so that it seems nothing has changed,
the index is destroyed.
But this way, there is no change in either the working tree
or the index, so it truly appears that the snapshot was taken
with _no_ visible effect of _any_ kind.
> suggest adding --index to stash snapshot

- README.md
The Git Alias file download link in  in Setup Section of the Readme file was broken.
> Fix Git Alias file download link in Setup Section

- gitalias.txt
This commit uses the %C(auto) color to adjust the
color of branch names. It makes them better readable since they will be bold and have different colors
depending on whether they are local branches or remote ones.
> Revise git ll / lll to coloring of normal git log

- gitalias.txt
Some of the git hew commands were missing the git command which was missed when moving from script to git alias.
Fixes #95
> Fix git hew

- README.md
- doc/git-cob/README.md
- doc/git-cob/index.md
- doc/index.md
- gitalias.txt
I truly use this all the time. However, I admit that I should probably be using `git topic-begin` a bit more instead.
Also, this PR fixes some broken links in the docs and adds some missing aliases to the indexes.
> Add git cob alias for checkout -b

- doc/install/index.md
I've just been through the hassle of setting up gitalias on Nix with Home Manager and I thought I might make a small contribution by adding some info to the Installation doc.
> Adding Nix + Home Manager to installation documentation

- doc/examples/index.md
- doc/git-publish/index.md
- doc/git-unpublish/index.md
- gitalias.txt
Adding an optional argument to `publish` and `unpublish` to specify the affected remote.
Current behavior stays consistent, the argument defaults to `origin`.
> Remote argument for publish and unpublish

- gitalias.txt
Executing shell using `!git` is unnecessary, because Git aliases by default prepend `git` to simple commands that don't start with `!`. Simpler version:
- Does exactly the same thing
- Is more concise
- Is more idiomatic Git alias syntax
- Avoids unnecessary shell execution overhead
> Remove unnecessary !git
